### ISSUE TITLE
Error loading CDN configuration: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by Topfunplus** [thirstywaterx/cdnsf#1]
the directory tree is :
├── cdn-config.json
├── cdn-loader.js
├── LICENSE
├── playground
│   └── index.html
└── README.md

1 directory, 5 files

and html:

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>hello!</h1>
    <script data-cdn="jquery,lodash" src="../cdn-loader.js" ></script>
  </body>
</html>

**Comment by thirstywaterx** [comment]
Fixed.
